package DataUtil;

public enum PermissionType {
	CommandHeal("HorizonEssentials.Heal"),
	CommandHealOther("HorizonEssentials.HealOther"),
	CommandFeed("HorizonEssentials.Feed"),
	CommandFeedOther("HorizonEssentials.FeedOther"),
	CommandChangeNickname("HorizonEssentials.ChangeNick"),
	CommandChangeNicknameOther("HorizonEssentials.ChangeNickOther"),
	CommandChangeMotd("HorizonEssentials.ChangeMotd"),
	CommandGetItem("HorizonEssentials.GetItem"),
	CommandsGameMode("HorizonEssentials.GameMode"),
	CommandTeleport("HorizonEssentials.Teleport"),
	CommandBroadcast("HorizonEssentials.Broadcast"),
	CommandSuicide("HorizonEssentials.Suicide"),
	CommandSlay("HorizonEssentials.Slay"),
	CommandKill("HorizonEssentials.Kill"),
	CommandWhisper("HorizonEssentials.Whisper"),
	CommandSay("HorizonEssentials.Say"),
	CommandLag("HorizonEssentials.ServerStatus"),
	ColorReplacer("HorizonEssentials.ReplaceColor"),
	CommandTpask("HorizonEssentials.Tpask"),
	CommandJump("HorizonEssentials.Jump"),
	CommandTpaccept("HorizonEssentials.Tpaccept"),
	CommandTpDeny("HorizonEssentials.TpDeny"),
	CommandTpaList("HorizonEssentials.TpaList"),
	CommandMute("HorizonEssentials.Mute"),
	CommandUnMute("HorizonEssentials.UnMute"),
	CommandSetWarp("HorizonEssentials.Setwarp"),
	CommandWarp("HorizonEssentials.Warp"),
	CommandOtherWarp("HorizonEssentials.WarpOther"),
	CommandRealName("HorizonEssentials.RealName"),
	CommandItemData("HorizonEssentials.ItemData"),
	CommandSpawn("HorizonEssentials.Spawn"),
	CommandSetSpawn("HorizonEssentials.SetSpawn"),
	CommandEconomy("HorizonEssentials.Economy"),
	CommandEconomySend("HorizonEssentials.EconomySend"),
	CommandTpall("HorizonEssentials.Tpall"),
	CommandWeather("HorizonEssentials.Weather"),
	CommandKillall("HorizonEssentials.Killall"),
	CommandWarpList("HorizonEssentials.WarpList"),
	CommandIgnore("HorizonEssentials.Ignore"),
	CommandTop("HorizonEssentials.Top"),
	CommandIgnoreChat("HorizonEssentials.IgnoreChat"),
	CommandIgnoretpa("HorizonEssentials.IgnoreTpa"),
	CommandIgnoreWhisper("HorizonEssentials.IgnoreWhisper"),
	CommandServer("HorizonEssentials.Server"),
	CommandFly("HorizonEssentials.Fly"),
	CommandMore("HorizonEssentials.More"),
	CommandBook("HorizonEssentials.Book"),
	CommandSetJail("HorizonEssentials.SetJail"),
	CommandTPDenyAll("HorizonEssentials.TPDenyAll"),
	CommandTempBan("HorizonEssentials.TempBan"),
	CommandUnban("HorizonEssentials.Unban"),
	CommandClearInventory("HorizonEssentials.ClearInventory"),
	CommandShock("HorizonEssentials.Shock"),
	CommandBreak("HorizonEssentials.CommandBreak"),
	CommandJail("HorizonEssentials.CommandJail"),
	CommandViewJail("HorizonEssentials.CommandViewJail"),
	CommandSummon("HorizonEssentials.CommandSummon"),
	CommandSethome("HorizonEssentials.CommandSetHome"),
	CommandHome("HorizonEssentials.CommandHome"),
	CommandSeen("HorizonEssentials.CommandSeen"),
	PassThroughCancelMove("HorizonEssentials.IgnoreCancelMove"),
	PassThroughCancelChat("HorizonEssentials.IgnoreCancelChat"),
	PassThroughCancelBlockBreak("HorizonEssentials.IgnoreCancelBlockBreak"),
	PassThroughCancelInteract("HorizonEssentials.IgnoreCancelInteract"),
	PassThroughCancelBlockDamage("HorizonEssentials.IgnoreCancelBlockDamage"),
	PassThroughCancelItemPickup("HorizonEssentials.IgnoreCancelItemPickup"),
	PassThroughCancelItemDrop("HorizonEssentials.IgnoreCancelItemDrop"),
	PassThroughCancelBlockPlace("HorizonEssentials.IgnoreCancelBlockPlace");
	private String value;
	private PermissionType (String value)
	{
		this.value  = value;
	}
	public String getValue(){
		return value;
	}
}
